// <auto-generated />
using System;
using EFCoreSinavProvaWFA1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EFCoreSinavProvaWFA1.Migrations
{
    [DbContext(typeof(KitapDukkaniContext))]
    partial class KitapDukkaniContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCoreSinavProvaWFA1.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"), 1L, 1);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.HasKey("AdminID");

                    b.ToTable("ADMINLER", (string)null);

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            KullaniciAdi = "admin",
                            Sifre = "21232F297A57A5A743894A0E4A801FC3"
                        });
                });

            modelBuilder.Entity("EFCoreSinavProvaWFA1.Models.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapID"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Durum")
                        .HasColumnType("NUMBER(1)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int?>("YayinEviID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("KitapID");

                    b.HasIndex("YayinEviID");

                    b.ToTable("KITAPLAR", (string)null);
                });

            modelBuilder.Entity("EFCoreSinavProvaWFA1.Models.YayinEvi", b =>
                {
                    b.Property<int>("YayinEviID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YayinEviID"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("YayinEviID");

                    b.ToTable("YAYINEVLERI", (string)null);
                });

            modelBuilder.Entity("EFCoreSinavProvaWFA1.Models.Kitap", b =>
                {
                    b.HasOne("EFCoreSinavProvaWFA1.Models.YayinEvi", "YayinEvi")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YayinEviID");

                    b.Navigation("YayinEvi");
                });

            modelBuilder.Entity("EFCoreSinavProvaWFA1.Models.YayinEvi", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
