// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ismailemregungorAlbumDukkani.Data;

#nullable disable

namespace ismailemregungorAlbumDukkani.Migrations
{
    [DbContext(typeof(MagazaContext))]
    partial class MagazaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ismailemregungorAlbumDukkani.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ALBUM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumID"), 1L, 1);

                    b.Property<string>("AlbumAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ALBUM_ADI");

                    b.Property<int>("AlbumDurumu")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ALBUM_DURUMU");

                    b.Property<double>("Fiyat")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("ALBUM_FİYATI");

                    b.Property<double?>("IndirimOrani")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("INDIRIM_ORANI");

                    b.Property<int>("SanatciID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("YayimTarihi")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("YAYIM_TARİHİ");

                    b.HasKey("AlbumID");

                    b.HasIndex("SanatciID");

                    b.ToTable("ALBUMLER", (string)null);
                });

            modelBuilder.Entity("ismailemregungorAlbumDukkani.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("KULLANICI_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("AD");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("KULLANICI_ADI");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SIFRE");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SOYAD");

                    b.HasKey("KullaniciID");

                    b.ToTable("KULLANICILAR", (string)null);

                    b.HasData(
                        new
                        {
                            KullaniciID = 1,
                            Ad = "Admin123",
                            KullaniciAdi = "Admin123",
                            Sifre = "3B612C75A7B5048A435FB6EC81E52FF92D6D795A8B5A9C17070F6A63C97A53B2",
                            Soyad = "Admin123"
                        });
                });

            modelBuilder.Entity("ismailemregungorAlbumDukkani.Models.Sanatci", b =>
                {
                    b.Property<int>("SanatciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SANATCI_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanatciID"), 1L, 1);

                    b.Property<string>("SanatciAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SANATCI_ADI");

                    b.HasKey("SanatciID");

                    b.ToTable("SANATCILAR", (string)null);
                });

            modelBuilder.Entity("ismailemregungorAlbumDukkani.Models.Album", b =>
                {
                    b.HasOne("ismailemregungorAlbumDukkani.Models.Sanatci", "Sanatci")
                        .WithMany("Albumler")
                        .HasForeignKey("SanatciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sanatci");
                });

            modelBuilder.Entity("ismailemregungorAlbumDukkani.Models.Sanatci", b =>
                {
                    b.Navigation("Albumler");
                });
#pragma warning restore 612, 618
        }
    }
}
