// <auto-generated />
using System;
using EFCoreModelFirst3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EFCoreModelFirst3.Migrations
{
    [DbContext(typeof(OkulContext))]
    partial class OkulContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCoreModelFirst3.Models.Ders", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersID"), 1L, 1);

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("EgitmenID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("DersID");

                    b.HasIndex("EgitmenID");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.Egitmen", b =>
                {
                    b.Property<int>("EgitmenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenID"), 1L, 1);

                    b.Property<string>("EgitmenAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EgitmenID");

                    b.ToTable("Egitmenler");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.EgitmenDers", b =>
                {
                    b.Property<int>("EgitmenDersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenDersID"), 1L, 1);

                    b.Property<int>("DersID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EgitmenID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("EgitmenDersID");

                    b.HasIndex("DersID");

                    b.HasIndex("EgitmenID");

                    b.ToTable("EgitmenDersleri");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"), 1L, 1);

                    b.Property<string>("OgrenciAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("OgrenciID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciDersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciDersID"), 1L, 1);

                    b.Property<int>("DersID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Not")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("OgrenciDersID");

                    b.HasIndex("DersID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("OgrenciDersleri");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.Ders", b =>
                {
                    b.HasOne("EFCoreModelFirst3.Models.Egitmen", null)
                        .WithMany("EgitmenDersleri")
                        .HasForeignKey("EgitmenID");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.EgitmenDers", b =>
                {
                    b.HasOne("EFCoreModelFirst3.Models.Ders", "Ders")
                        .WithMany("EgitmenDersleri")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreModelFirst3.Models.Egitmen", "Egitmen")
                        .WithMany()
                        .HasForeignKey("EgitmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Egitmen");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.OgrenciDers", b =>
                {
                    b.HasOne("EFCoreModelFirst3.Models.Ders", "Ders")
                        .WithMany("OgrenciDersleri")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreModelFirst3.Models.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersleri")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.Ders", b =>
                {
                    b.Navigation("EgitmenDersleri");

                    b.Navigation("OgrenciDersleri");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.Egitmen", b =>
                {
                    b.Navigation("EgitmenDersleri");
                });

            modelBuilder.Entity("EFCoreModelFirst3.Models.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDersleri");
                });
#pragma warning restore 612, 618
        }
    }
}
